name: windows-msvc-build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.27.0"

      - name: run build
        uses: lukka/run-cmake@v10.3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DIS_CI_BUILD=true']"
          buildPreset: 'ninja-multi-vcpkg'

      - name: run unit tests
        run: |
          echo "Running seika tests!"
          ${{ github.workspace }}\builds\Debug\seika_test.exe
